export const wearableData = [
    {
        id: 0,
        modelLink: "models/All For One/AllForOneWing.glb",
        imageLink: { imageLink_1: "../images/AllForOneLowerbody.png", imageLink_2: "../images/AllForOneTopHead.png", fontsize: 10 },
        wearableDetails: { name: "FantasticLand 2022 - All For One", fontsize: 18},
        description: "*Wearables are in limited supply and will be collected through a raffle.Participants who have attended the 2022 Chinese New Year Carnival and played the Treasure Hunt Game in Dragon City, Decentraland before 4:00 p.m., January 31 UTC are eligible for the NFT wearable raffle.",
        revealTime: "The results will be revealed after: 4:00 p.m., January 31 UTC",
        designer: "Designed & Created by Avatar Network",
        totalSupply: "1840",
    },
    {
        id: 1,
        modelLink: "models/dR.X/DR.XEyewear.glb",
        imageLink: { imageLink_1: "../images/dR.XEyewear.png", imageLink_2: "../images/dR.XUpperbody.png", fontsize: 10 },
        wearableDetails: { name: "FantasticLand 2022 - dR.X", fontsize: 18},
        description: "*Wearables are in limited supply and will be collected through a raffle.Participants who have attended the 2022 Chinese New Year Carnival and played the Treasure Hunt Game in Dragon City, Decentraland before 4:00 p.m., January 31 UTC are eligible for the NFT wearable raffle.",
        revealTime: "The results will be revealed after: 4:00 p.m., January 31 UTC",
        designer: "Designed & Created by Avatar Network",
        totalSupply: "1840",
    },
    {
        id: 2,
        modelLink: "models/YAMAN/YamanHelmet.glb",
        imageLink: { imageLink_1: "../images/YamanHelmet.png", imageLink_2: "../images/YamanLowerbody.png", fontsize: 10 },
        wearableDetails: { name: "FantasticLand 2022 - Yaman", fontsize: 18},
        description: "*Wearables are in limited supply and will be collected through a raffle.Participants who have attended the 2022 Chinese New Year Carnival and played the Treasure Hunt Game in Dragon City, Decentraland before 4:00 p.m., January 31 UTC are eligible for the NFT wearable raffle.",
        revealTime: "The results will be revealed after: 4:00 p.m., January 31 UTC",
        designer: "Designed & Created by Avatar Network",
        totalSupply: "1840",
    },
    {
        id: 3,
        modelLink: "models/Kiko/kikoupperbody.glb",
        imageLink: { imageLink_1: "../images/KikoHelmet.png", imageLink_2: "../images/KikoLowerbody.png", fontsize: 10 },
        wearableDetails: { name: "FantasticLand 2022 - Kiko", fontsize: 18},
        description: "*Wearables are in limited supply and will be collected through a raffle.Participants who have attended the 2022 Chinese New Year Carnival and played the Treasure Hunt Game in Dragon City, Decentraland before 4:00 p.m., January 31 UTC are eligible for the NFT wearable raffle.",
        revealTime: "The results will be revealed after: 4:00 p.m., January 31 UTC",
        designer: "Designed & Created by Avatar Network",
        totalSupply: "1840",
    },
    {
        id: 4,
        modelLink: "models/Nancy/NancyLowerbody.glb",
        imageLink: { imageLink_1: "../images/NancyLowerbody.png", imageLink_2: "../images/NancyUpperbody.png", fontsize: 10 },
        wearableDetails: { name: "FantasticLand 2022 - Nancy", fontsize: 18},
        description: "*Wearables are in limited supply and will be collected through a raffle.Participants who have attended the 2022 Chinese New Year Carnival and played the Treasure Hunt Game in Dragon City, Decentraland before 4:00 p.m., January 31 UTC are eligible for the NFT wearable raffle.",
        revealTime: "The results will be revealed after: 4:00 p.m., January 31 UTC",
        designer: "Designed & Created by Avatar Network",
        totalSupply: "1840",
    },
]